<a href="https://colab.research.google.com/github/hrithikRag/Password-Strength-prediction/blob/main/Password_prediction_ANNs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [112]:
df=pd.read_csv('/content/drive/MyDrive/Password data/data.csv', error_bad_lines=False)
df

Skipping line 2810: expected 2 fields, saw 5
Skipping line 4641: expected 2 fields, saw 5
Skipping line 7171: expected 2 fields, saw 5
Skipping line 11220: expected 2 fields, saw 5
Skipping line 13809: expected 2 fields, saw 5
Skipping line 14132: expected 2 fields, saw 5
Skipping line 14293: expected 2 fields, saw 5
Skipping line 14865: expected 2 fields, saw 5
Skipping line 17419: expected 2 fields, saw 5
Skipping line 22801: expected 2 fields, saw 5
Skipping line 25001: expected 2 fields, saw 5
Skipping line 26603: expected 2 fields, saw 5
Skipping line 26742: expected 2 fields, saw 5
Skipping line 29702: expected 2 fields, saw 5
Skipping line 32767: expected 2 fields, saw 5
Skipping line 32878: expected 2 fields, saw 5
Skipping line 35643: expected 2 fields, saw 5
Skipping line 36550: expected 2 fields, saw 5
Skipping line 38732: expected 2 fields, saw 5
Skipping line 40567: expected 2 fields, saw 5
Skipping line 40576: expected 2 fields, saw 5
Skipping line 41864: expected 2 field

password  strength
0           kzde5577         1
1           kino3434         1
2          visi7k1yr         1
3           megzy123         1
4        lamborghin1         1
...              ...       ...
669635    10redtux10         1
669636     infrared1         1
669637  184520socram         1
669638     marken22a         1
669639      fxx4pw4g         1

[669640 rows x 2 columns]

In [113]:
df.shape

(669640, 2)

In [114]:
df.describe()

strength
count  669640.000000
mean        0.990196
std         0.507948
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669640 entries, 0 to 669639
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   password  669639 non-null  object
 1   strength  669640 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 10.2+ MB


In [116]:
df[df['password'].isnull()]

password  strength
367579      NaN         0

In [117]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 669639 entries, 0 to 669639
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   password  669639 non-null  object
 1   strength  669639 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 15.3+ MB


In [118]:
df.head(5)

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

Data preparation before modelling it

In [119]:
df_array=np.array(df)
df_array

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

In [120]:
import random
random.shuffle(df_array)

In [121]:
password=[label[0] for label in df_array]
strength=[label[1] for label in df_array]


In [122]:
def alphabet_splitter(str):
    lst=[]
    for i in str:
        lst.append(i)
    return lst

In [123]:
alphabet_splitter('abcdefghij')

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [124]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [125]:
vector_converter=TfidfVectorizer(tokenizer=alphabet_splitter)

In [126]:
password_vec=vector_converter.fit_transform(password)

In [127]:
password_vec.shape

(669639, 133)

In [128]:
type(password_vec)

scipy.sparse._csr.csr_matrix

In [129]:
characters = vector_converter.get_feature_names_out()
print(characters)

['\x01' '\x05' '\x06' '\x08' '\x0f' '\x10' '\x11' '\x16' '\x17' '\x19'
 '\x1b' '\x1c' '\x1e' ' ' '!' '"' '#' '$' '%' '&' '(' ')' '*' '+' '-' '.'
 '/' '0' '1' '2' '3' '4' '5' '6' '7' '8' '9' ';' '<' '=' '>' '?' '@' '['
 '\\' ']' '^' '_' '`' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm'
 'n' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '{' '|' '}' '~'
 '\x7f' '\x81' '\x8d' '\xa0' '¡' '¦' '§' '¨' '«' '¯' '°' '±' '²' '³' '´'
 'µ' '¶' '·' '¹' 'º' '¼' '¾' '¿' '×' 'ß' 'à' 'á' 'â' 'ä' 'å' 'æ' 'ç' 'è'
 'é' 'ê' 'í' 'î' 'ï' 'ð' 'ñ' 'ò' 'ó' 'ô' 'õ' '÷' 'ú' 'û' 'ü' 'ý' 'þ' 'ÿ'
 '—' '‚' '™']


In [130]:
first_password_vector=password_vec[0]
first_password_vector.T.todense()

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56706108],
        [0.        ],
        [0.59135491],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [131]:
first_password_dataframe=pd.DataFrame(first_password_vector.T.todense(), index=vector_converter.get_feature_names_out(), columns=["TF-IDF"])

In [132]:
first_password_dataframe.sort_values(by=['TF-IDF'],ascending=False)

TF-IDF
7   0.591355
5   0.567061
z   0.336105
k   0.291752
d   0.285902
..       ...
=   0.000000
<   0.000000
;   0.000000
9   0.000000
™   0.000000

[133 rows x 1 columns]

In [133]:
strength=np.array(strength)
password_vec = password_vec.toarray()

In [134]:
print(type(strength),type(password_vec))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


Applying PCA

In [135]:
from sklearn.decomposition import PCA

In [136]:
pca=PCA(n_components=2)
password_vec_transformed=pca.fit_transform(password_vec)
p_comps=pca.components_
explained_variance_ratio=pca.explained_variance_ratio_
#print(p_comps)
print(explained_variance_ratio)

[0.05237146 0.04684962]


In [137]:
from sklearn.model_selection import train_test_split

In [138]:
X_train,X_test,y_train,y_test=train_test_split(password_vec,strength,test_size=0.2)

In [139]:
X_train.shape

(535711, 133)

In [140]:
#from sklearn.linear_model import LogisticRegression

In [141]:
#classifier=LogisticRegression(random_state=45, multi_class='multinomial')

In [142]:
#classifier.fit(X_train,y_train)

In [143]:
#y_pred=classifier.predict(X_test)
#y_pred

In [144]:
#from sklearn.metrics import confusion_matrix,accuracy_score

In [145]:
#cm_logistic=confusion_matrix(y_test,y_pred)
#print(cm_logistic)
#print(accuracy_score(y_test,y_pred))

In [146]:
#from sklearn.metrics import classification_report
#print(classification_report(y_test,y_pred))

In [147]:
#from sklearn.tree import DecisionTreeClassifier

In [148]:
#tree_classifier=DecisionTreeClassifier(criterion='entropy', splitter='best', random_state = 100, max_depth=40, min_samples_leaf=5)

In [149]:
#tree_classifier.fit(X_train,y_train)

In [150]:
#y_pred=tree_classifier.predict(X_test)
#y_pred

In [151]:
#cm_decision_tree=confusion_matrix(y_test,y_pred)
#print(cm_decision_tree)
#print(accuracy_score(y_test,y_pred))

In [152]:
#from sklearn.ensemble import RandomForestClassifier

In [153]:
#forest_classifier=RandomForestClassifier(n_estimators=100, random_state = 100, max_depth=50, criterion='entropy', min_samples_leaf=5)

In [154]:
#forest_classifier.fit(X_train,y_train)

In [155]:
#y_pred=forest_classifier.predict(X_test)
#y_pred

In [156]:
#cm_random_forest=confusion_matrix(y_test,y_pred)
#print(cm_random_forest)
#print(accuracy_score(y_test,y_pred))

applying artificial neural networks


In [157]:
'''X_tr = tf.data.Dataset.from_tensor_slices(X_tr)
X_tr = X_tr.cache()
X_tr = X_tr.shuffle(len(X_tr))
X_tr = X_tr.batch(128)
X_tr = X_tr.prefetch(64)'''

'X_tr = tf.data.Dataset.from_tensor_slices(X_tr)\nX_tr = X_tr.cache()\nX_tr = X_tr.shuffle(len(X_tr))\nX_tr = X_tr.batch(128)\nX_tr = X_tr.prefetch(64)'

In [158]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [159]:
# Define the number of classes and input dimension
num_classes = 3
input_dim= X_train.shape[1]
# Create a sequential model
model = Sequential()

# Adding the input layer
model.add(Dense(units=100, activation='relu', input_dim=input_dim))  # Replace input_dim with your input dimension

# Adding more hidden layers
#model.add(tf.keras.layers.Dropout(0.2))
model.add(Dense(units=300, activation='relu'))
model.add(Dense(units=200, activation='relu'))
model.add(Dense(units=100, activation='relu'))
# Adding the output layer with softmax activation for multi-class classification
model.add(Dense(units=num_classes, activation='softmax'))

# Define the Adam optimizer and specify the learning rate
adam_optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

# Compile the model
model.compile(optimizer=adam_optimizer, loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 100)               13400     
                                                                 
 dense_16 (Dense)            (None, 300)               30300     
                                                                 
 dense_17 (Dense)            (None, 200)               60200     
                                                                 
 dense_18 (Dense)            (None, 100)               20100     
                                                                 
 dense_19 (Dense)            (None, 3)                 303       
                                                                 
Total params: 124303 (485.56 KB)
Trainable params: 124303 (485.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [160]:
model.fit(X_train, y_train, batch_size=500, epochs=100)

Epoch 1/100
1072/1072 [==============================] - 5s 4ms/step - loss: 0.3940 - sparse_categorical_accuracy: 0.8215
Epoch 2/100
1072/1072 [==============================] - 5s 4ms/step - loss: 0.2412 - sparse_categorical_accuracy: 0.8984
Epoch 3/100
1072/1072 [==============================] - 4s 3ms/step - loss: 0.1363 - sparse_categorical_accuracy: 0.9494
Epoch 4/100
1072/1072 [==============================] - 4s 4ms/step - loss: 0.1023 - sparse_categorical_accuracy: 0.9626
Epoch 5/100
1072/1072 [==============================] - 5s 4ms/step - loss: 0.0825 - sparse_categorical_accuracy: 0.9701
Epoch 6/100
1072/1072 [==============================] - 4s 4ms/step - loss: 0.0706 - sparse_categorical_accuracy: 0.9746
Epoch 7/100
1072/1072 [==============================] - 4s 4ms/step - loss: 0.0632 - sparse_categorical_accuracy: 0.9773
Epoch 8/100
1072/1072 [==============================] - 4s 4ms/step - loss: 0.0580 - sparse_categorical_accuracy: 0.9793
Epoch 9/100
1072/1072 [=

In [161]:
adam_optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)    #further optimizing by decreasing the learning rate

In [ ]:
model.fit(X_train, y_train, batch_size=500, epochs=50)

Epoch 1/50
1072/1072 [==============================] - 4s 4ms/step - loss: 0.0050 - sparse_categorical_accuracy: 0.9983
Epoch 2/50
1072/1072 [==============================] - 5s 4ms/step - loss: 0.0056 - sparse_categorical_accuracy: 0.9981
Epoch 3/50
1072/1072 [==============================] - 4s 3ms/step - loss: 0.0059 - sparse_categorical_accuracy: 0.9980
Epoch 4/50
1072/1072 [==============================] - 4s 4ms/step - loss: 0.0051 - sparse_categorical_accuracy: 0.9983
Epoch 5/50
1072/1072 [==============================] - 5s 4ms/step - loss: 0.0045 - sparse_categorical_accuracy: 0.9984
Epoch 6/50
1072/1072 [==============================] - 4s 3ms/step - loss: 0.0054 - sparse_categorical_accuracy: 0.9982
Epoch 7/50
1072/1072 [==============================] - 4s 4ms/step - loss: 0.0047 - sparse_categorical_accuracy: 0.9983
Epoch 8/50
1072/1072 [==============================] - 5s 4ms/step - loss: 0.0054 - sparse_categorical_accuracy: 0.9982
Epoch 9/50
1072/1072 [==========

In [164]:
test_loss, test_accuracy= model.evaluate(X_test, y_test)
print(test_accuracy)

4186/4186 [==============================] - 10s 2ms/step - loss: 0.0301 - sparse_categorical_accuracy: 0.9950
0.9949749112129211


In [165]:
output_values= model.predict(X_test)
y_pred= np.argmax(output_values, axis=1)
print(y_pred)

4186/4186 [==============================] - 13s 3ms/step
[1 2 1 ... 1 1 1]


In [166]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[17934   158     0]
 [  270 98919   110]
 [    4   131 16402]]
